version: "3"
services:
  api:
    container_name: api
    image: piotrostr/realtime
    build: .
    env_file: .env
    depends_on: [db]
  db:
    container_name: db
    image: arangodb/arangodb
    env_file: .env
    ports:
      - 8529:8529
